// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"ginblog/blog/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/blogs/create",
				Handler: CreateBlogHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/blogs/list",
				Handler: GetBlogListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/users/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/users/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
	)
}
