// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type Blog struct {
	ID      int64  `json:"id"`      //博客的唯一ID
	Title   string `json:"title"`   //博客标题
	Content string `json:"content"` //博客内容
	UserID  int64  `json:"user_id"` //博客作者的ID
	Author  string `json:"author"`  //博客作者的用户名
}

type BlogListRes struct {
	Blogs []Blog `json:"blogs"` //博客列表
}

type CreateBlogReq struct {
	Title   string `json:"title"`   //博客标题
	Content string `json:"content"` //博客内容
}

type CreateBlogRes struct {
	BlogID int64 `json:"blog_id"` //创建成功后返回博客的ID
}

type GetBlogListReq struct {
	Page     int64 `json:"page"`      //当前页码
	PageSize int64 `json:"page_size"` //每页显示的博客数量
}

type LoginReq struct {
	Username string `json:"username"` //登录用户名
	Password string `json:"password"` //登录密码
}

type LoginRes struct {
	Token string `json:"token"` //登录成功后返回token
}

type RegisterReq struct {
	Username string `json:"username"` //注册用户名
	Password string `json:"password"` //注册密码
}

type User struct {
	ID       int64  `json:"id"`       //用户的唯一ID
	Username string `json:"username"` //用户名
}
