// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package blog_model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	blogsFieldNames          = builder.RawFieldNames(&Blogs{})
	blogsRows                = strings.Join(blogsFieldNames, ",")
	blogsRowsExpectAutoSet   = strings.Join(stringx.Remove(blogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	blogsRowsWithPlaceHolder = strings.Join(stringx.Remove(blogsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	blogsModel interface {
		Insert(ctx context.Context, data *Blogs) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Blogs, error)
		Update(ctx context.Context, data *Blogs) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBlogsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Blogs struct {
		Id         int64     `db:"id"`
		Title      string    `db:"title"`
		Content    string    `db:"content"`
		UserId     int64     `db:"user_id"`
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
	}
)

func newBlogsModel(conn sqlx.SqlConn) *defaultBlogsModel {
	return &defaultBlogsModel{
		conn:  conn,
		table: "`blogs`",
	}
}

func (m *defaultBlogsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBlogsModel) FindOne(ctx context.Context, id int64) (*Blogs, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", blogsRows, m.table)
	var resp Blogs
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBlogsModel) Insert(ctx context.Context, data *Blogs) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, blogsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Title, data.Content, data.UserId)
	return ret, err
}

func (m *defaultBlogsModel) Update(ctx context.Context, data *Blogs) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, blogsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Title, data.Content, data.UserId, data.Id)
	return err
}

func (m *defaultBlogsModel) tableName() string {
	return m.table
}
